stages:
  - build
  - deploy

before_script:
  - export IMAGE_TAG="$CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG"
  - export REGISTRY_PATH="$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  - export HAPROXY_REGISTRY_PATH="$CI_REGISTRY_IMAGE/haproxy:$IMAGE_TAG"

neoscan-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $REGISTRY_PATH .
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push $REGISTRY_PATH
    - "[ \"$CI_COMMIT_REF_SLUG\" == \"master\" ] && docker tag $REGISTRY_PATH $CI_REGISTRY_IMAGE"
    - "[ \"$CI_COMMIT_REF_SLUG\" == \"master\" ] && docker push $CI_REGISTRY_IMAGE"

haproxy-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - cd haproxy && docker build -t $HAPROXY_REGISTRY_PATH .
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push $HAPROXY_REGISTRY_PATH

staging:
  stage: deploy
  environment: staging
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml up -d
  variables:
    HOST: neoscan.backslash.fr
  tags:
    - staging
  when: manual

production:
  stage: deploy
  environment: production
  script:
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml up -d
  variables:
    HOST: neoscan.io
  tags:
    - production
  when: manual
  only:
    - master
