language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0
script:
  - "mix local.rebar --force"
  - "mix local.hex --force"
  - "mix deps.get"
  - "MIX_ENV=travis mix test"
  - "mix credo --strict"
services:
  - postgresql
addons:
  postgresql: "9.4"
